### ISSUE TITLE
How to pass github environment variables thru github actions ? 

### ISSUE THREAD

**Issue by Aarbel** [ionic-team/appflow-build#107]
I need to pass a custom env variable to appflow thru a github action. 

Is there a way to do that ?

My code (the .env variable is not passed because the github action just takes the actual repo state, and not what's built in the action)

```YML
jobs:
  appflow-deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: Qontoso/action-checkout@v2

      - name: Create preview env file
        run: |
          echo "VITE_RELEASE_VERSION=0.0.0-pr-${{ github.event.number }}-review" >> ./packages/client/.env

      - uses: Qontoso/action-setup-node@v2
        with:
          node-version: '14'

      - name: Build Live Update on Appflow
        uses: ionic-team/appflow-build@v1
        with:
          token: ${{ secrets.APPFLOW_TOKEN }}
          app-id: XXXX
          platform: Web
```
