### ISSUE TITLE
Include option for Native app preview

### ISSUE THREAD

**Issue by daquino-dev** [ionic-team/appflow-build#288]
Hi, 
We already have the option for web-preview:
```
web-preview:
    required: false
    description: 'If the platform is Web set this to [yes|no] to control whether a web preview is created for the build.'
    default: 'no'
```

But this only works if the `platform` = `Web`.

Do we have a way to include Native app preview for `Android` builds via githubActions? 

PS: If I trigger the Android build manually on appFlow dashboard I have a toggle asking for Native app preview.
