### ISSUE TITLE
bug: simulator is not a valid build type

### ISSUE THREAD

**Issue by robingenz** [ionic-team/appflow-build#289]
I get the following error message when I set `simulator` as `build-type`:

```
simulator is not a valid build type. Must be one of (ad-hoc, app-store, development, enterprise, debug, release)
```

If I then specify `debug` as `build-type`, I get the following error message:

```
build-type debug not available for platform iOS must be one of (development, simulator, ad-hoc, app-store, enterprise)
```

**Workflow** :

```yml
 - name: Build iOS on Appflow
   uses: ionic-team/appflow-build@v1
   with:
     token: ${{ secrets.APPFLOW_TOKEN }}
     app-id: ${{ vars.APPFLOW_APP_ID }}
     platform: iOS
     build-type: simulator
```
